insert into users (id, username, password) values (null, 'admin', 'admin');
insert into county_entity (county_id, name) values (null, 'Vilniaus');
insert into county_entity (county_id, name) values (null, 'Kauno');
insert into district_entity (district_id, adress, county_id, name, number_of_electors) values (null, 'Gedimino g. 9', 1, 'Centro', 1000);
insert into district_entity (district_id, adress, county_id, name, number_of_electors) values (null, 'Panerių g. 55', 1, 'Panarų', 2000);
insert into district_entity (district_id, adress, county_id, name, number_of_electors) values (null, 'Žaliakalnio g. 1', 2, 'Žaliakalnio', 1500);
insert into district_entity (district_id, adress, county_id, name, number_of_electors) values (null, 'Kalhozo g. 9', 2, 'Kaimo', 2000);
insert into district_representative_entity (id, district_id, name, surname) values (null, 1, 'Marek', 'Visluhij');
insert into district_representative_entity (id, district_id, name, surname) values (null, 2, 'Ponas', 'Binas');
insert into district_representative_entity (id, district_id, name, surname) values (null, 3, 'Aliukas', 'Brolis');
insert into district_representative_entity (id, district_id, name, surname) values (null, 4, 'Kaimo', 'Jurgis');
insert into party_entity (party_id, name, party_number) values (null, 'Darbo Partija', 5);
insert into party_entity (party_id, name, party_number) values (null, 'Valstiečių Partija', 7);
insert into party_entity (party_id, name, party_number) values (null, 'Nakties Partija', 1001);
insert into party_entity (party_id, name, party_number) values (null, 'Apokalipses Partija', 666);
insert into party_entity (party_id, name, party_number) values (null, 'Valinsko Partija', 901);
insert into party_entity (party_id, name, party_number) values (null, '69 Danguje Partija', 69);
